[package]
name = "spi-flash"
version = "0.2.2"
authors = ["Adam Greig <adam@adamgreig.com>"]
edition = "2018"
repository = "https://github.com/adamgreig/spi-flash-rs"
license = "Apache-2.0 OR MIT"
description = "SPI flash memory interface crate"

[dependencies]
log = "0.4.11"
anyhow = "1.0.34"
thiserror = "1.0.22"
num_enum = "0.5.1"
jep106 = "= 0.2.4"
indicatif = "0.15.0"
